from typing import Protocol
from .contracts import PricingPage, PricingSnapshot

class PricingRepository(Protocol):
    def get(self, identifier: str, actor_id: int) -> PricingSnapshot | None: ...
    def list_for_user(self, actor_id: int, cursor: str | None = None, limit: int = 50) -> PricingPage: ...
