from typing import Protocol
from .contracts import TrackingPage, TrackingSnapshot

class TrackingRepository(Protocol):
    def get(self, identifier: str, actor_id: int) -> TrackingSnapshot | None: ...
    def list_for_user(self, actor_id: int, cursor: str | None = None, limit: int = 50) -> TrackingPage: ...
