from typing import Protocol
from .contracts import JourneyPage, JourneySnapshot

class JourneyRepository(Protocol):
    def get(self, identifier: str, actor_id: int) -> JourneySnapshot | None: ...
    def list_for_user(self, actor_id: int, cursor: str | None = None, limit: int = 50) -> JourneyPage: ...
